### ISSUE TITLE
Maybe add 'DELETE' 

### ISSUE THREAD

**Issue by rcsmit** [Sven-Bo/google-sheets-data-entry-form-with-streamlit#1]
Maybe add a delete? And a button to see the whole dataframe and/or 1 row? Then the CRUD is complete :)

**Comment by Sven-Bo** [comment]
@rcsmit Hey there! Noticed you took the new delete button for a test drive and cleared the sample data. 😅 Looks like it works! Remember, with great power comes great responsibility. 😉 Also, it'd be super helpful if you could keep the sample data intact. I'm planning to use it for a tutorial. Thanks!

**Comment by rcsmit** [comment]
I think I didnt delete anything?
