### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by MohammedMusharraf11** [Sven-Bo/google-sheets-data-entry-form-with-streamlit#2]
Thanks a lot sir but i m encountering with an error 
My app is working well when i locally host my app and it is even appending the data in my sheets but when i deploy it i m getting this as error
ModuleNotFoundError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "/mount/src/appointments/appointments.py", line 4, in <module>
    from streamlit_gsheets import GSheetsConnection

**Comment by Sven-Bo** [comment]
Ensure to also include the requirements.txt file in your GitHub repo
